export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const LOAD_AUTHENTICATED_USER_REQUEST = 'auth/LOAD_AUTHENTICATED_USER_REQUEST';
export const LOAD_AUTHENTICATED_USER_SUCCESS = 'auth/LOAD_AUTHENTICATED_USER_SUCCESS';
export const LOAD_AUTHENTICATED_USER_FAILURE = 'auth/LOAD_AUTHENTICATED_USER_FAILURE';