spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pontotest
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  profiles:
    active: test
  devtools:
    restart.enabled: true
    livereload.enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        generate_statistics: false
        hbm2ddl.import_files: import-dev.sql
        jdbc:
          lob:
            non_contextual_creation: true
security:
  basic:
    enabled=false:

management.security.enabled: false
management.health.db.enabled: false