spring:
  profiles:
    active: prod
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  # Keep the connection alive if idle for a long time
  datasource:
    test-while-idle: false
    validation-query: SELECT 1
    continue-on-error: true
  jpa:
    show-sql: false
    generate-ddl: false
    properties:
      hibernate.generate_statistics: false

