spring:
  application.name: Ponto
  datasource:
    url: jdbc:postgresql://localhost:5432/ponto
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
  jackson.serialization.write_dates_as_timestamps: false
server:
  compression:
    enabled: true
    mime-types: application/javascript,application/json,text/css,text/html
  port: 8080

security:
  basic:
    enabled=false:
ponto:
  jwt:
    secret: PontoSecret
    expiration: 604800